### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by GuilhermeMorais** [refaelyehuda/check-duplicate-nuget-packages#1]
Hi guys, 

   The Tools seems not to be working. In my projects, I have a nugget `WebGrease`, which are in 2 different projects: WebClient with the `version 1.1.0` and the Unit Test project with the `version 1.6.0`. Both folders are there: `WebGrease.1.1.0` and `WebGrease.1.6.0` but the tool didn't get the error. 

   Any Tips to fix that?

Kind Regards.

**Comment by refaelyehuda** [comment]
What is the search pattern that you set?

**Comment by GuilhermeMorais** [comment]
Hi, well I used the default one `(\.+[\d]+)`. Is it not right?

**Comment by refaelyehuda** [comment]
Can you share with me your build step configuration? your build machine is Linux or Windows?
